stages:
  - name: stunning-parakeet
    dockerfile: Dockerfile
    push: false
    run: true
    runOptions:
      volume:
        - deploy/build
        - /build
    tagType: tag
    environments:
      - production
    branches:
      - master
  - name: stunning-parakeet
    dockerfile: Dockerfile
    push: false
    run: false
    tagType: tag
    environments:
      - production
    branches:
      - develop
