stages:
  - name: stunning-parakeet
    dockerfile: Dockerfile
    push: false
    run: true
    tagType: tag
    environments:
      - production
    branches:
      - master
  - name: stunning-parakeet
    dockerfile: Dockerfile
    push: false
    run: false
    tagType: tag
    environments:
      - production
    branches:
      - develop
