stages:
  - name: stunning-parakeet
    dockerfile: Dockerfile
    push: false
    run: true
    runOptions:
      volume:
        - deploy/build
        - /build
    environments:
      - staging
    deployments:
      - name: test
        job_file: nomad.json
  - name: gcr.io/kindrid-stage/stunning-parakeet
    dockerfile: deploy/Dockerfile
    push: true
    run: false
    environments:
      - production
